name: publish-blog-site
on:
  push:
    branches:    
      - master
jobs:
  publish-blog-site: 
    name: publish blog site
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2
        run: rm -rf docs
      - uses: jakejarvis/hugo-build-action@master
        with:
          args: mod get -u
      - uses: jakejarvis/hugo-build-action@master
        with:
          args: --gc --minify --cleanDestinationDir -d docs
        run: |
          git status
          ls -al
