name: publish-blog-site
on:
  push:
    branches:    
      - main
jobs:
  publish-blog-site: 
    name: publish blog site
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: remove docs
        run: rm -rf docs
      - name: hugo mod get
        uses: jakejarvis/hugo-build-action@master
        with:
          args: mod get -u
      - name: hugo build
        uses: jakejarvis/hugo-build-action@master
        with:
          args: --gc --minify --cleanDestinationDir -d docs
      - name: test
        run: |
          git status
          ls -al
