name: publish-blog-site
on:
  push:
    branches:    
      - master
jobs:
  publish-blog-site: 
    name: publish blog site
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: |
          echo $PATH
